<?php

/**
 * Implments hook_theme().
 */
function questline_engage_theme($existing, $type, $theme, $path) {
  $modulePath = '/' . drupal_get_path('module', 'questline_engage');
  $imagePath = $modulePath . '/js/plugins/engagearticlesearch/images/';

  return [
    'article_preview_template' => [
      'variables' => [
        'article' => NULL
      ],
    ],
    'search_dialog_template' => [
      'variables' => [
        'imagePath' => $imagePath
      ]
    ]
  ];
}